FROM mcr.microsoft.com/dotnet/sdk:10.0.301-alpine3.24 AS build
WORKDIR /source

COPY global.json Directory.Build.props CabeNaSemana.slnx ./
COPY src/CabeNaSemana.Domain/CabeNaSemana.Domain.csproj src/CabeNaSemana.Domain/
COPY src/CabeNaSemana.Application/CabeNaSemana.Application.csproj src/CabeNaSemana.Application/
COPY src/CabeNaSemana.Infrastructure/CabeNaSemana.Infrastructure.csproj src/CabeNaSemana.Infrastructure/
COPY src/CabeNaSemana.Api/CabeNaSemana.Api.csproj src/CabeNaSemana.Api/
RUN dotnet restore src/CabeNaSemana.Api/CabeNaSemana.Api.csproj

COPY src/ src/
RUN dotnet publish src/CabeNaSemana.Api/CabeNaSemana.Api.csproj \
    --configuration Release \
    --no-restore \
    --output /app/publish \
    /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:10.0.9-alpine3.24 AS runtime
WORKDIR /app
ENV ASPNETCORE_HTTP_PORTS=8080 \
    DOTNET_EnableDiagnostics=0
EXPOSE 8080

RUN apk add --no-cache krb5-libs tzdata
COPY --from=build /app/publish ./
USER $APP_UID
ENTRYPOINT ["dotnet", "CabeNaSemana.Api.dll"]
